/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote */
        post: operations["promote_admin_promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/pending-recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending Recipes */
        get: operations["pending_recipes_admin_pending_recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recipes/{recipe_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Recipe */
        post: operations["approve_recipe_admin_recipes__recipe_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recipes/{recipe_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Recipe */
        post: operations["reject_recipe_admin_recipes__recipe_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/pending-ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending Ingredients */
        get: operations["pending_ingredients_admin_pending_ingredients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ingredients/{submission_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Ingredient */
        post: operations["approve_ingredient_admin_ingredients__submission_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ingredients/{submission_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Ingredient */
        post: operations["reject_ingredient_admin_ingredients__submission_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description íì¬ í í°ì ì¦ì ë¬´í¨ííë¤. í¤ëê° ìê±°ë ì´ë¯¸ ë¬´í¨í í í°ì´ì´ë ì¡°ì©í ì±ê³µì¼ë¡
         *     ì²ë¦¬íë¤ - ë¡ê·¸ììì ì´ì°¨í¼ 'ë¡ê·¸ì¸ ì ë ìíë¡ ë§ë¤ê¸°'ê° ëª©ì ì´ê¸° ëë¬¸ì´ë¤.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_profile__user_id__get"];
        /** Update Profile */
        put: operations["update_profile_profile__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Profile */
        post: operations["create_profile_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pantry/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pantry */
        get: operations["list_pantry_pantry__user_id__get"];
        put?: never;
        /** Add Pantry */
        post: operations["add_pantry_pantry__user_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pantry/{user_id}/{ingredient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Pantry Expiry
         * @description ëì¥ê³  íë©´ ê°í¸(2026-07-19): ëª©ë¡ìì ì íµê¸°íì ë°ë¡ ìì í  ì ìê² íë¤.
         */
        put: operations["update_pantry_expiry_pantry__user_id___ingredient_id__put"];
        post?: never;
        /** Remove Pantry */
        delete: operations["remove_pantry_pantry__user_id___ingredient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/safety/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Safety */
        post: operations["check_safety_safety_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/safety/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Safety Overview
         * @description ë³´ì  ì¬ë£ ì ì²´ë¥¼ í ë²ì íì´ì ì ì²´/ì£¼ì/ì ìì¼ë¡ ì§ê³íë¤.
         *     get_all_recalls()ë ì¬ë£ ê°ìì ë¬´ê´íê² 1ë²ë§ í¸ì¶íë¤(N+1 ë°©ì§).
         */
        get: operations["safety_overview_safety_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/recipes/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Popular Recipes
         * @description ì¦ê²¨ì°¾ê¸° íë©´ì "ìì¦ ì¸ê¸° ìë ë ìí¼" ì¹ì(2026-07-21, #req5) - ë¡ê·¸ì¸ ì¬ë¶ì
         *     ë¬´ê´íê² ë³¼ ì ìë ê³µê° ì ë³´ë¼ ì¸ê°ë¥¼ ìêµ¬íì§ ìëë¤(search_all_recipesì ëì¼í ë°©ì¹¨).
         */
        get: operations["get_popular_recipes_recommendation_recipes_popular_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/recipes/{recipe_id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Like Status */
        get: operations["get_like_status_recommendation_recipes__recipe_id__like_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/recipes/{recipe_id}/like/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Like */
        post: operations["toggle_like_recommendation_recipes__recipe_id__like_toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recommend Demo
         * @description ë¡ê·¸ì¸ ìì´ ì¶ì² ë¡ì§ë§ ì²´ííë ë°ëª¨ì© ìëí¬ì¸í¸(2026-08-10).
         *
         *     ì¤ì  ìë¹ì¤ë íìê°ìê³¼ 5ë¨ê³ ì¨ë³´ë©ì ê±°ì³ì¼ ì¶ì² íë©´ì ë¿ëë¤. í¬í¸í´ë¦¬ì¤
         *     ë§í¬ë¥¼ ë°ì ì¬ëì´ ê·¸ ê³¼ì  ìì´ íµì¬ ê¸°ë¥ì ë°ë¡ ë³¼ ì ìëë¡ ì¸ê° ìì´ ì´ì´ëë¤.
         *     íë¡íì DBìì ì½ì§ ìê³  ì¿¼ë¦¬ë¡ ë°ì ìë ë¥´ê¸°ë§ì¼ë¡ ì¦ììì ë§ë ë¤ - ìë³¸
         *     ë¡ì§ì´ íë¡íìì ì¤ì ë¡ ì°¸ì¡°íë ê°ì´ ìë ë¥´ê¸° íëë¿ì´ë¼ ê°ë¥íë¤.
         *
         *     ê³µê° ìëí¬ì¸í¸ì´ë¯ë¡ ê°ì¸ ë°ì´í°(pantry/ì¦ê²¨ì°¾ê¸° ë±)ë ì¼ì  ê±´ëë¦¬ì§ ìê³ ,
         *     ë¨ì© ì ìë² ë¶íê° ì»¤ì§ì§ ìëë¡ ì¬ë£ ê°ìì ê²°ê³¼ ê°ìë¥¼ ìíì¼ë¡ ë¬¶ëë¤.
         */
        get: operations["recommend_demo_recommendation_demo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommend */
        get: operations["recommend_recommendation__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/{user_id}/alternative/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alternative
         * @description "ì´ ë©ë´ê° ì«ë¤ë©´?" ë²í¼(2026-07-21, #req6) - recipe_idì ììêµ°ê³¼ ê°ì¼ë©´ì
         *     ì¹¼ë¡ë¦¬ê° ê°ì¥ ë¹ì·í ë¤ë¥¸ ë ìí¼ë¥¼ ì¬ë£ì ë¬´ê´íê² íë ê³¨ë¼ì¤ë¤.
         */
        get: operations["get_alternative_recommendation__user_id__alternative__recipe_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/recipes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Recipes
         * @description í íë©´ "ì´ ë¬ì ì ì²  ì¬ë£" ìì ê´ë ¨ ë ìí¼ë¥¼ ë³´ì¬ì¤ ë ì´ë¤(2026-07-21, #req7).
         *     íë¡í/ìë ë¥´ê¸° íí° ìë ê³µê° ì¡°íë¼ recommend()ì ë¬ë¦¬ ì¸ê°ë¥¼ ìêµ¬íì§ ìëë¤.
         */
        get: operations["search_recipes_recommendation_recipes_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_recommendation_recipes__recipe_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Favorites */
        get: operations["list_favorites_favorites__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{user_id}/{recipe_id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle */
        post: operations["toggle_favorites__user_id___recipe_id__toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_reviews__recipe_id__get"];
        put?: never;
        /** Create Review */
        post: operations["create_review_reviews__recipe_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{recipe_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_reviews__recipe_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/recipes/{recipe_id}/substitution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Substitution Info */
        get: operations["get_substitution_info_recommendation_recipes__recipe_id__substitution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/popular-videos/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_popular_videos_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/popular-videos/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Videos */
        get: operations["get_videos_popular_videos__category__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Ingredients */
        get: operations["search_ingredients_ingredients_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients/{user_id}/{food_code}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Ingredient Favorite */
        post: operations["toggle_ingredient_favorite_ingredients__user_id___food_code__toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients/{user_id}/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Favorite Ingredients */
        get: operations["list_favorite_ingredients_ingredients__user_id__favorites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my-recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Recipes */
        get: operations["list_my_recipes_my_recipes_get"];
        put?: never;
        /** Submit Recipe */
        post: operations["submit_recipe_my_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my-recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe Detail */
        get: operations["get_recipe_detail_my_recipes__recipe_id__get"];
        /** Update Recipe */
        put: operations["update_recipe_my_recipes__recipe_id__put"];
        post?: never;
        /** Delete Recipe */
        delete: operations["delete_recipe_my_recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/recipes/{recipe_id}/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe Price */
        get: operations["get_recipe_price_recommendation_recipes__recipe_id__price_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/recipes/{recipe_id}/nutrition-fit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Nutrition Fit */
        get: operations["get_nutrition_fit_recommendation_recipes__recipe_id__nutrition_fit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/recipes/{recipe_id}/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recipe Ingredients Scaled
         * @description ê°êµ¬ì ìì ë§ì¶° íì°ë ì¬ë£ ìë ëª©ë¡. portion_agent.py ë¡ì§ ê·¸ëë¡ ì¬ì¬ì©íë¤.
         */
        get: operations["get_recipe_ingredients_scaled_recommendation_recipes__recipe_id__ingredients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasonal/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Season */
        get: operations["get_current_season_seasonal_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasonal/{user_id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Seasonal Matches */
        get: operations["get_seasonal_matches_seasonal__user_id__matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation/recipes/{recipe_id}/shopping-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shopping Links For Missing */
        get: operations["get_shopping_links_for_missing_recommendation_recipes__recipe_id__shopping_links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredient-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Submissions */
        get: operations["list_my_submissions_ingredient_submissions_get"];
        put?: never;
        /** Submit Ingredient */
        post: operations["submit_ingredient_ingredient_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredient-submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission Detail */
        get: operations["get_submission_detail_ingredient_submissions__submission_id__get"];
        /** Update Submission */
        put: operations["update_submission_ingredient_submissions__submission_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Coverage */
        Coverage: {
            /** Total */
            total: number;
            /** Matched */
            matched: number;
            /** Missing */
            missing: number;
            /** Coverage Pct */
            coverage_pct: number | null;
        };
        /** ExcludedCost */
        ExcludedCost: {
            /** Ingredient */
            ingredient: string;
            /** Reason */
            reason: string;
        };
        /** ExpiryUpdateRequest */
        ExpiryUpdateRequest: {
            /** Expiry Date */
            expiry_date?: string | null;
        };
        /** FavoriteItem */
        FavoriteItem: {
            /** Id */
            id: number;
            /** Menu Name */
            menu_name: string;
            /** Category */
            category: string | null;
            /** Calorie */
            calorie: number | null;
            /** Created At */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncludedCost */
        IncludedCost: {
            /** Ingredient */
            ingredient: string;
            /** Matched Name */
            matched_name: string;
            /** Amount G */
            amount_g: number;
            /** Cost */
            cost: number;
            /** Is Estimated */
            is_estimated: boolean;
        };
        /** IngredientDisplayItem */
        IngredientDisplayItem: {
            /** Name */
            name: string;
            /** Display */
            display: string;
            /** Amount */
            amount: number | null;
            /** Unit */
            unit: string | null;
        };
        /** IngredientSafetyStatus */
        IngredientSafetyStatus: {
            /** Name */
            name: string;
            /** Expiry Date */
            expiry_date: string | null;
            /** Status */
            status: string;
            /** Recall Summary */
            recall_summary: string;
            /** Expiry Status */
            expiry_status: string | null;
        };
        /** IngredientSearchResponse */
        IngredientSearchResponse: {
            /** Total */
            total: number;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
        };
        /** LikeStatus */
        LikeStatus: {
            /** Liked */
            liked: boolean;
            /** Like Count */
            like_count: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** User Id */
            user_id: number;
            /** Token */
            token: string;
        };
        /** MatchedIngredient */
        MatchedIngredient: {
            /** Ingredient */
            ingredient: string;
            /** Item Name */
            item_name: string;
            /** Unit */
            unit: string;
            /** Price */
            price: number;
            /** Ratio */
            ratio: number | null;
        };
        /** MissingIngredient */
        MissingIngredient: {
            /** Ingredient */
            ingredient: string;
            /** Suggestion */
            suggestion: string;
            /** Type */
            type: string;
        };
        /** MyRecipeDetail */
        MyRecipeDetail: {
            /** Menu Name */
            menu_name: string;
            /** Category */
            category: string | null;
            /** Calorie */
            calorie: number | null;
            /** Ingredients Text */
            ingredients_text: string;
            /** Steps Text */
            steps_text: string;
        };
        /** MyRecipeItem */
        MyRecipeItem: {
            /** Id */
            id: number;
            /** Menu Name */
            menu_name: string;
            /** Category */
            category: string | null;
            /** Calorie */
            calorie: number | null;
            /** Status */
            status: string;
            /** Like Count */
            like_count: number;
        };
        /** MySubmissionDetail */
        MySubmissionDetail: {
            /** Ingredient Name */
            ingredient_name: string;
            /** Calorie */
            calorie: number | null;
            /** Carbs G */
            carbs_g: number | null;
            /** Protein G */
            protein_g: number | null;
            /** Fat G */
            fat_g: number | null;
            /** Sodium Mg */
            sodium_mg: number | null;
            /** Price Per 100G */
            price_per_100g: number | null;
        };
        /** MySubmissionItem */
        MySubmissionItem: {
            /** Id */
            id: number;
            /** Ingredient Name */
            ingredient_name: string;
            /** Calorie */
            calorie: number | null;
            /** Status */
            status: string;
        };
        /** NutritionFitResponse */
        NutritionFitResponse: {
            /** Available */
            available: boolean;
            /** Bracket Label */
            bracket_label: string;
            /** Is Estimated */
            is_estimated: boolean;
            /** Rows */
            rows: components["schemas"]["NutritionRow"][];
            sodium_row: components["schemas"]["SodiumRow"] | null;
            /** Micro Is Partial */
            micro_is_partial: boolean;
            /** Condition Notes */
            condition_notes: string[];
        };
        /** NutritionRow */
        NutritionRow: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Target */
            target: number;
            /** Provided */
            provided: number;
            /** Pct Of Daily */
            pct_of_daily: number | null;
            /** Already Supplemented */
            already_supplemented: boolean;
        };
        /** PantryItem */
        PantryItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Expiry Date */
            expiry_date: string | null;
        };
        /** PantryItemRequest */
        PantryItemRequest: {
            /** Name */
            name: string;
            /** Expiry Date */
            expiry_date?: string | null;
        };
        /** PendingIngredient */
        PendingIngredient: {
            /** Id */
            id: number;
            /** Ingredient Name */
            ingredient_name: string;
            /** Calorie */
            calorie: number | null;
            /** Carbs G */
            carbs_g: number | null;
            /** Protein G */
            protein_g: number | null;
            /** Fat G */
            fat_g: number | null;
            /** Sodium Mg */
            sodium_mg: number | null;
            /** Price Per 100G */
            price_per_100g: number | null;
            /** Username */
            username: string;
        };
        /** PendingRecipe */
        PendingRecipe: {
            /** Id */
            id: number;
            /** Menu Name */
            menu_name: string;
            /** Category */
            category: string | null;
            /** Calorie */
            calorie: number | null;
            /** Username */
            username: string;
        };
        /** PopularRecipeItem */
        PopularRecipeItem: {
            /** Id */
            id: number;
            /** Menu Name */
            menu_name: string;
            /** Category */
            category: string | null;
            /** Calorie */
            calorie: number | null;
            /** Like Count */
            like_count: number;
        };
        /** PopularVideo */
        PopularVideo: {
            /** Video Title */
            video_title: string;
            /** Channel Title */
            channel_title: string;
            /** Video Id */
            video_id: string;
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Video Url */
            video_url: string;
            /** View Count */
            view_count: number;
            /** Fetched At */
            fetched_at: string;
        };
        /** PriceResponse */
        PriceResponse: {
            /** Tier */
            tier: string;
            /** Matched */
            matched: components["schemas"]["MatchedIngredient"][];
            /** Unmatched */
            unmatched: string[];
            /** Total Cost */
            total_cost: number;
            /** Included */
            included: components["schemas"]["IncludedCost"][];
            /** Excluded */
            excluded: components["schemas"]["ExcludedCost"][];
        };
        /** ProfileGetResponse */
        ProfileGetResponse: {
            /** Has Profile */
            has_profile: boolean;
            /** Gender */
            gender?: string | null;
            /** Age Group */
            age_group?: string | null;
            /** Allergy */
            allergy?: string | null;
            /** Health Goal */
            health_goal?: string | null;
            /** Purpose */
            purpose?: string | null;
            /** Cooking Level */
            cooking_level?: string | null;
            /** Supplements */
            supplements?: string | null;
            /** Household Size */
            household_size?: number | null;
            /** Novelty Pref */
            novelty_pref?: string | null;
            /** Cooking Tools */
            cooking_tools?: string | null;
            /** Medical Conditions */
            medical_conditions?: string | null;
        };
        /** ProfileRequest */
        ProfileRequest: {
            /** Gender */
            gender: string;
            /** Age Group */
            age_group: string;
            /** Allergy */
            allergy: string;
            /** Health Goal */
            health_goal: string;
            /** Purpose */
            purpose: string;
            /** Cooking Level */
            cooking_level: string;
            /** Supplements */
            supplements: string;
            /** Household Size */
            household_size: number;
            /** Novelty Pref */
            novelty_pref: string;
            /** Cooking Tools */
            cooking_tools: string;
            /**
             * Medical Conditions
             * @default
             */
            medical_conditions: string;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** User Id */
            user_id: number;
        };
        /** PromoteRequest */
        PromoteRequest: {
            /** Code */
            code: string;
        };
        /** PromoteResponse */
        PromoteResponse: {
            /** Is Admin */
            is_admin: boolean;
        };
        /** RecipeDetail */
        RecipeDetail: {
            /** Id */
            id: number;
            /** Menu Name */
            menu_name: string;
            /** Cook Method */
            cook_method: string | null;
            /** Category */
            category: string | null;
            /** Calorie */
            calorie: number | null;
            /** Nutrition Group */
            nutrition_group: string;
            /** Nutrients Json */
            nutrients_json: string | null;
            /** Steps Json */
            steps_json: string | null;
            /** Youtube Url */
            youtube_url: string | null;
            /** Image Url */
            image_url: string | null;
        };
        /** RecipeSubmitRequest */
        RecipeSubmitRequest: {
            /** Menu Name */
            menu_name: string;
            /** Category */
            category: string;
            /** Calorie */
            calorie?: number | null;
            /** Ingredients Text */
            ingredients_text: string;
            /** Steps Text */
            steps_text: string;
        };
        /** RecipeSubmitResponse */
        RecipeSubmitResponse: {
            /** Recipe Id */
            recipe_id: number;
            /** Status */
            status: string;
        };
        /** RecipeSummary */
        RecipeSummary: {
            /** Id */
            id: number;
            /** Menu Name */
            menu_name: string;
            /** Category */
            category: string | null;
            /** Calorie */
            calorie: number | null;
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Id */
            id: number;
            /** Menu Name */
            menu_name: string;
            /** Category */
            category: string | null;
            /** Calorie */
            calorie: number | null;
            /** Nutrition Group */
            nutrition_group: string;
            /** Image Url */
            image_url: string | null;
            /** Youtube Url */
            youtube_url: string | null;
            /** Ingredient Overlap */
            ingredient_overlap: number;
            /** Coverage Ratio */
            coverage_ratio: number;
            /** Qualifies */
            qualifies: boolean;
            /** Has Protein Match */
            has_protein_match: boolean;
            /** Energy Kcal */
            energy_kcal?: number | null;
            /** Protein G */
            protein_g?: number | null;
            /** Fat G */
            fat_g?: number | null;
            /** Carbs G */
            carbs_g?: number | null;
        };
        /** ReviewItem */
        ReviewItem: {
            /** Rating */
            rating: number;
            /** Review Text */
            review_text: string;
            /** Created At */
            created_at: string;
            /** Username */
            username: string;
            /** Image Url */
            image_url?: string | null;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** User Id */
            user_id: number;
            /** Rating */
            rating: number;
            /** Review Text */
            review_text: string;
            /** Image Url */
            image_url?: string | null;
        };
        /** SafetyCheckRequest */
        SafetyCheckRequest: {
            /** Ingredient Name */
            ingredient_name: string;
            /** Expiry Date */
            expiry_date?: string | null;
        };
        /** SafetyCheckResponse */
        SafetyCheckResponse: {
            /** Recall Matches */
            recall_matches: {
                [key: string]: unknown;
            }[];
            /** Expiry Status */
            expiry_status: string | null;
            /** Saved Notes */
            saved_notes: number;
        };
        /** SafetyOverviewResponse */
        SafetyOverviewResponse: {
            /** Total */
            total: number;
            /** Warning Count */
            warning_count: number;
            /** Normal Count */
            normal_count: number;
            /** Items */
            items: components["schemas"]["IngredientSafetyStatus"][];
        };
        /** SeasonalMatchResponse */
        SeasonalMatchResponse: {
            /** Month */
            month: number;
            /** Seasonal Ingredients */
            seasonal_ingredients: string[];
            /** Matches */
            matches: string[];
        };
        /** SeasonalResponse */
        SeasonalResponse: {
            /** Month */
            month: number;
            /** Ingredients */
            ingredients: string[];
        };
        /** ShoppingLink */
        ShoppingLink: {
            /** Ingredient */
            ingredient: string;
            /** Naver */
            naver: string;
            /** Coupang */
            coupang: string;
        };
        /** ShoppingLinksResponse */
        ShoppingLinksResponse: {
            /** Links */
            links: components["schemas"]["ShoppingLink"][];
        };
        /** SignupRequest */
        SignupRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** SignupResponse */
        SignupResponse: {
            /** User Id */
            user_id: number;
            /** Token */
            token: string;
        };
        /** SodiumRow */
        SodiumRow: {
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Limit */
            limit: number;
            /** Provided */
            provided: number;
            /** Pct Of Limit */
            pct_of_limit: number;
            /** Limit Adjusted */
            limit_adjusted: boolean;
        };
        /** SubmissionRequest */
        SubmissionRequest: {
            /** Ingredient Name */
            ingredient_name: string;
            /** Calorie */
            calorie?: number | null;
            /** Carbs G */
            carbs_g?: number | null;
            /** Protein G */
            protein_g?: number | null;
            /** Fat G */
            fat_g?: number | null;
            /** Sodium Mg */
            sodium_mg?: number | null;
            /** Price Per 100G */
            price_per_100g?: number | null;
        };
        /** SubmissionResponse */
        SubmissionResponse: {
            /** Submission Id */
            submission_id?: number | null;
            /** Status */
            status: string;
        };
        /** SubstitutionResponse */
        SubstitutionResponse: {
            coverage: components["schemas"]["Coverage"];
            /** Missing Ingredients */
            missing_ingredients: components["schemas"]["MissingIngredient"][];
        };
        /** SummaryResponse */
        SummaryResponse: {
            /** Summary */
            summary: string | null;
        };
        /** ToggleResponse */
        ToggleResponse: {
            /** Favorited */
            favorited: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    promote_admin_promote_post: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pending_recipes_admin_pending_recipes_get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingRecipe"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_recipe_admin_recipes__recipe_id__approve_post: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_recipe_admin_recipes__recipe_id__reject_post: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pending_ingredients_admin_pending_ingredients_get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingIngredient"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_ingredient_admin_ingredients__submission_id__approve_post: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_ingredient_admin_ingredients__submission_id__reject_post: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_profile__user_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileGetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_profile__user_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_profile_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pantry_pantry__user_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PantryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_pantry_pantry__user_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PantryItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pantry_expiry_pantry__user_id___ingredient_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
                ingredient_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpiryUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_pantry_pantry__user_id___ingredient_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
                ingredient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_safety_safety_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SafetyCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    safety_overview_safety_overview_get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_popular_recipes_recommendation_recipes_popular_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PopularRecipeItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_like_status_recommendation_recipes__recipe_id__like_get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_like_recommendation_recipes__recipe_id__like_toggle_post: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_demo_recommendation_demo_get: {
        parameters: {
            query?: {
                ingredients?: string[];
                allergy?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_recommendation__user_id__get: {
        parameters: {
            query?: {
                limit?: number;
                ingredients?: string[];
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alternative_recommendation__user_id__alternative__recipe_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_recipes_recommendation_recipes_search_get: {
        parameters: {
            query?: {
                keyword?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_recommendation_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favorites_favorites__user_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_favorites__user_id___recipe_id__toggle_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_reviews__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_reviews__recipe_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_reviews__recipe_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_substitution_info_recommendation_recipes__recipe_id__substitution_get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubstitutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_popular_videos_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_videos_popular_videos__category__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PopularVideo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_ingredients_ingredients_search_get: {
        parameters: {
            query?: {
                keyword?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_ingredient_favorite_ingredients__user_id___food_code__toggle_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
                food_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favorite_ingredients_ingredients__user_id__favorites_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_recipes_my_recipes_get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyRecipeItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_recipe_my_recipes_post: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_detail_my_recipes__recipe_id__get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyRecipeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recipe_my_recipes__recipe_id__put: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipe_my_recipes__recipe_id__delete: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_price_recommendation_recipes__recipe_id__price_get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nutrition_fit_recommendation_recipes__recipe_id__nutrition_fit_get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionFitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_ingredients_scaled_recommendation_recipes__recipe_id__ingredients_get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientDisplayItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_season_seasonal_current_get: {
        parameters: {
            query?: {
                month?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_seasonal_matches_seasonal__user_id__matches_get: {
        parameters: {
            query?: {
                month?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonalMatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shopping_links_for_missing_recommendation_recipes__recipe_id__shopping_links_get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingLinksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_submissions_ingredient_submissions_get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MySubmissionItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_ingredient_ingredient_submissions_post: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_detail_ingredient_submissions__submission_id__get: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MySubmissionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_submission_ingredient_submissions__submission_id__put: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
